### ISSUE TITLE
Shape visual issue

### ISSUE THREAD

**Issue by proxiti** [chrisbanes/haze#132]
## Information
  - Haze version: 0.5.3
  - Platform: Android13
  - Compose version: 1.6.0

## Expected Behavior
Correct rounded corners without white lines.

## Actual Behavior
The rounded corners have white lines.
![82f8537e02f1434d9c89d49b192b394](https://github.com/chrisbanes/haze/assets/25367586/ff6469b2-54bc-40a7-8732-d8a4696bf34e)
![72b678ad9c8f1c0ea63edab7f1d035e](https://github.com/chrisbanes/haze/assets/25367586/7848fc2e-d44c-4dcd-873e-81b8ab7dedfc)

## Steps to Reproduce the Problem
```kotlin
Box {
  Image(
      modifier = Modifier
          .fillMaxSize()
          .haze(
              state = hazeState
          ),
      painter = painterResource(
          id = R.drawable.test
      ),
      contentDescription = "",
      contentScale = ContentScale.Crop
  )

  Box(
      modifier = Modifier
          .align(Alignment.Center)
          .padding(horizontal = 14.dp)
          .height(80.dp)
          .fillMaxWidth()
          .hazeChild(
              state = hazeState,
              shape = RoundedCornerShape(20.dp),
              style = HazeStyle(noiseFactor = 0f, tint = Color.Black.copy(.6f))
          ),
  )
}
```

**Comment by chrisbanes** [comment]
So this is caused by rounding + anti-aliasing on our clip paths. We clip twice, once for the blurred shape, and clip out'ing the content behind. The antialiasing means that the edges are aliases and have some translucency. Since we're clipping twice, the float rounding means that there's a chance that the blurred content won't cover the very edges of the clipped out content behind (which is the white parts you're seeing).

I've got a hacky fix in #133 which basically shrinks the clip out shape by 1px on all sides, so that there's always something drawn behind the blurred content. This won't work for all shapes though, as we need to resize the outline. I'm going to have a think today if there's a better way.
