### ISSUE TITLE
iOS native view is not rendered when haze is applied

### ISSUE THREAD

**Issue by colin-weng-s** [chrisbanes/haze#239]
## Information

  - Haze version: 0.7.2
  - Platform: iOS (iPhone 15 Pro simulator running on iOS 17.2)

I want to blur all the contents on the screen below a snackbar, on Android it works, but on iOS,
when there are composables that contain implemented iOS native views, they are not rendered.
The blur effect itself is correct.

## Expected Behavior

on Android, it works.

[Screen_recording_20240620_193618.webm](https://github.com/chrisbanes/haze/assets/167203772/bcf1cee1-24b6-45ec-8da1-53b56add261d)

## Actual Behavior

on iOS, the Toggle is broken only during haze is used.

https://github.com/chrisbanes/haze/assets/167203772/113ecdb1-3333-4010-abbd-c601b09c200a

## Steps to Reproduce the Problem

1. implement a native iOS view:

```kotlin 
// ThemedSwitch.ios.kt
@Composable
actual fun ThemedSwitch(
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
) {
    val appContext = koinInject<AppContext>()
    val viewModel = remember { SwitchViewModel(onCheckedChange) }
    LaunchedEffect(checked) {
        viewModel.isChecked = checked
    }
    UIKitViewController(
        modifier = Modifier.size(55.dp, 33.dp),
        factory = { appContext.uiViewControllerContext.componentFactories.switchFactory(viewModel) },
        update = {},
    )
}
```

```swift
struct SwitchView: View {
    @ObservedObject var viewModel: SwitchViewModelWrapper
    
    var body: some View {
        Toggle("", isOn: $viewModel.isChecked)
            .tint(Color(uiColor: ColorHelper().toUIColor(color: Colors().brandNormal)))
            .labelsHidden()
            .padding()
    }
}
```

View model implementations are omitted because it's not related, I think. If you need it please tell me.

2. Use haze for the snackbar

```kotlin

// App composable
AppTheme {
    GuardSignIn { isLoggedIn ->
        val initialScreen = remember(isLoggedIn) {
            if (isLoggedIn) MainScreen.createHome() else SignInScreen
        }
        Box(
            modifier = Modifier.fillMaxSize()
                .background(brush = Colors.gradientBackground)
                .haze(koinInject()) // the app-wide HazeState
        ) {
           // screen contents that need to be blurred
        }
    }

    koinInject<SnackbarController>().Compose()
}

// SnackbarController.Compose()
Box(
    modifier = Modifier
        .padding(16.dp)
        .fillMaxWidth()
        .height(56.dp)
        .hazeChild(koinInject<HazeState>(), shape = shape, style = HazeStyle(blurRadius = 10.dp))
        .shadow(elevation = 8.dp, shape = shape),
) {
  // contents
}

```

**Comment by rschattauer** [comment]
@chrisbanes , is that something 0.9 is fixing or is there no possibility for this topic?

**Comment by chrisbanes** [comment]
I haven't tried, but it might help

**Comment by rschattauer** [comment]
@chrisbanes I tried it and it seems [0.9.0-alpha07](https://github.com/chrisbanes/haze/releases/tag/0.9.0-alpha07) works somewhat-ish, just materials wasn't something I could use as it was showing some weird effects (almost fully translucent). Here is a SwiftUI map in the background within a Scaffold with Floating Action Buttons with custom HazeStyle.

```
style = HazeStyle(
     backgroundColor = FloatingActionButtonDefaults.containerColor,
    tint = FloatingActionButtonDefaults.containerColor.copy(alpha = 0.3f),
    blurRadius = 148.dp,
),
```

The thing is that this looks different on iOS and Android and also I would assume that with such a high blurRadius I wouldn't see any text through at all, but it's readable on both? (look at the bottom FAB, I was playing around with that one)

<img width="559" alt="Screenshot 2024-08-18 at 09 22 02" src="https://github.com/user-attachments/assets/b25ccbc8-8133-4c67-9941-7f34f0ac1984">

Should I create a new issue or do you want to use this here?

**Comment by chrisbanes** [comment]
My guess is that the map content isn't actually being drawn in the blur iOS, and what you're seeing is the white background being blurred.

I need a sample to see what's really happening though. If someone wants to send a PR for a quick MapView sample that would help immensely. Otherwise I'll see if I can find some time.

**Comment by chrisbanes** [comment]
Yeah that would work, or a PR adding it to the samples in this repo. Either works.

**Comment by rschattauer** [comment]
https://github.com/rschattauer/compose_multiplatform/
Branch: [broken-haze-on-map](https://github.com/rschattauer/compose_multiplatform/tree/broken-haze-on-map)
Feel free to copy stuff as you wish into haze as a sample.

In the README it's stated on how to add your private MapBox keys.
There is `val useUIKitInsteadOfSwiftUI = false` that you can make true to also see the same (not working) effect on UIKitView instead of UIKitViewController if that even makes a difference.
On the home and map screen you will find a top bar that has the haze effect activated.

Android:
<img width="352" alt="Screenshot 2024-08-21 at 13 51 09" src="https://github.com/user-attachments/assets/33a74065-3c7b-4081-8027-179038420396">
<img width="354" alt="Screenshot 2024-08-21 at 13 51 14" src="https://github.com/user-attachments/assets/321baa94-2d70-4b7a-be98-332518508f70">

iOS:
<img width="619" alt="Screenshot 2024-08-21 at 13 56 08" src="https://github.com/user-attachments/assets/6ef28354-ab21-4969-923b-ed221664375e">
<img width="617" alt="Screenshot 2024-08-21 at 13 56 15" src="https://github.com/user-attachments/assets/57e6d0ce-8285-445b-84dc-a8452967c119">


If there is anything else I can help you with, please let me know.

**Comment by markst** [comment]
Hope you don't mind me commenting on this issue, but equally happy to create a new _issue_.

Thought I'd just share some experience which I believe is somewhat similar to the issue I have with liquid:
https://github.com/FletchMcKee/liquid/issues/70#issuecomment-4658057464

> Might add here, that we're embedding each of our Composables inside a `ComposeUIViewController` which are then placed within a `UINavigationController`. So when using the liquid it's not rendering on iOS.

Seems the haze doesn't work when applying to a `ComposeUIViewController`?

Implementation: https://github.com/markst/weatherdrive-app/blob/31b7511da8f66ef0531bc9ae9b923d8859eeb38c/composeApp/src/commonMain/kotlin/com/weatherdrive/App.kt#L51

<br>

| Android | iOS (player not tab bar) |
|---|---|
| ![Video](https://github.com/user-attachments/assets/068afcbf-f3c0-497d-a6bd-b590a69e471b) | <img width="295" height="640" alt="Image" src="https://github.com/user-attachments/assets/332f9e1a-248d-4bb2-b6b6-e08f8e67ee20" /> |

**Comment by chrisbanes** [comment]
@markst That should totally work. Yeah please create a new issue (or I can)

**Comment by markst** [comment]
https://github.com/chrisbanes/haze/issues/977
